# Set variables once
variables:
  cleanChekout: 'false'
  solutionType: angularDotNetCore # angularDotNetCore, dotNetCore
  apiDirectory: 'ServiceWebsite/ServiceWebsite'
  nodeVersion: 10.16.0
  sonarCloudPrepareExtraProperties: |
    sonar.exclusions=**/node_modules/**,**/*.spec.ts,*.spec.ts,**/ClientApp/*,**/ClientApp/src/*,**/ClientApp/coverage/**/*,**/*.js
    sonar.typescript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/ServiceWebsite/ServiceWebsite/ClientApp/coverage/lcov.info,**/lcov.info
    sonar.typescript.exclusions=**/node_modules/**,**/typings.d.ts,**/main.ts,**/environments/environment*.ts,**/*routing.module.ts,**/api-client.ts
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
  coverletCoverageExclusions: '[ServiceWebsite.BookingApi.Client]*,[ServiceWebsite.UserAPI.Client]*,[*]ServiceWebsite.Swagger.*,[ServiceWebsite]ServiceWebsite.Program,[ServiceWebsite]ServiceWebsite.Startup,[ServiceWebsite]ServiceWebsite.ConfigureServicesExtensions,[ServiceWebsite.IntegrationTests]*,[ServiceWebsite.UnitTests]*'
  integrationTestsAppSettingsTransform: '
  "AzureAd/Authority":"https://login.microsoftonline.com/$(TenantId)",
  "AzureAd/ClientId":"$(vh-user-api-appid)",
  "AzureAd/ClientSecret":"$(vh-service-web-key)",
  "AzureAd:TenantId":"$(TenantId)",
  "AzureAd:VhServiceResourceId":"$(vh-service-web-appid)", 
  "VhServices/BookingsApiResourceId":"$(vh-bookings-api-identifieruris)",
  "VhServices:KinlySelfTestScoreEndpointUrl": "https://dev.self-test.hearings.hmcts.net/api/v1/testcall",
  "VhServices:PexipSelfTestNodeUri": "sip.dev.self-test.hearings.hmcts.net",
  "AzureStorage/BaseVideoUrl":"https://vhcoreinfrapreview.blob.core.windows.net/video",
  "CustomToken/Secret":"$(hmac-secret-key)",
  "ClientId":"$(vh-service-web-appid)",
  "ClientSecret":"$(vh-service-web-key)"
    '
  vhAzureKeyVault: 'https://vhwebsitepreview.vault.azure.net/' # Used during integration tests
  keyVaultName: vhcoreinfrahtpreview # Used to get secrets for integration tests
  secretsFilter: 'TenantId,hmac-secret-key,vh-service-web-appid,vh-service-web-key,vh-bookings-api-identifieruris' # filters out secrets returned from key vault

# GitHub Repo that contains build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    endpoint: 'GitHubDevOps'

trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*
pr:
  - master

jobs:
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    cleanCheckout: $(cleanCheckout)
    sonarCloudExtraProperties: $(sonarCloudPrepareExtraProperties)
    KeyVaultName: $(KeyVaultName)
    apiDirectory: $(apiDirectory)
    SecretsFilter: $(SecretsFilter)
    solutionType: $(solutionType)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    dotNetCoreVersion: '3.1.100'
    nodeVersion: '10.x'
