export const Paths = {
    AboutVideoHearings: 'about-video-hearings',
    AboutYouAndYourClient: 'about-you-and-your-client',
    AboutYou: 'about-you-rep',
    AccessToRoom: 'access-to-a-room-rep',
    AboutYourClient: 'about-your-client',
    ClientAttendance: 'client-attendance',
    HearingSuitability: 'hearing-suitability',
    YourComputer: 'your-computer-rep',
    AboutYourComputer: 'about-your-computer-rep',
    QuestionnaireCompleted:'questionnaire-completed',
    PleaseContactUs:'contact-us-rep',
    ThankYou: 'thank-you-rep',
    ContactUs:'contact-us-rep',
};
